# Generated by Django 5.0.6 on 2024-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_no',
            field=models.TextField(),
        ),
    ]
