# Generated by Django 5.0.6 on 2024-07-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_departments_dept_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dept_no',
            new_name='dept_description',
        ),
    ]
